---
  apiVersion: v1
  kind: Service
  metadata:
    name: mobile-simulator-service
    labels:
      app: mobile-simulator
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
    selector:
      app: mobile-simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-simulator-deployment
  labels:
    app: mobile-simulator
spec:
  selector:
    matchLabels:
      app: mobile-simulator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-simulator
    spec:
      containers:
        - image: mobile-simulator-service:1.0
          imagePullPolicy: Always
          name: mobile-simulator
          resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
          envFrom:
            - secretRef:
                name: mobile-simulator-secrets
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mobile-simulator-service
spec:
  to:
    kind: Service
    name: mobile-simulator-service

